version: "3.8"
services:
  db:
    image: docker.io/library/postgres:alpine
    environment:
      - POSTGRES_PASSWORD=wisdom
      - POSTGRES_DB=wisdom
      - POSTGRES_USER=wisdom
    networks:
      - dbnet
# Disabled because this doesn't work properly on MacOS.
# [33] CONTEXT:  writing block 0 of relation base/16384/2658
# 2023-01-17 21:46:56.579 UTC [33] LOG:  out of file descriptors: No file descriptors available; release and retry
#    volumes:
#      - $PWD/db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  prometheus:
    image: docker.io/prom/prometheus
    command:
      - --config.file=/opt/prometheus/prometheus.yaml
      - --web.enable-lifecycle
    volumes:
      - $PWD/prometheus/:/opt/prometheus/
    ports:
      - "9090:9090"
    networks:
      - dbnet
  grafana:
    image: docker.io/grafana/grafana:7.5.17
    environment:
      - GF_LOG_LEVEL=warn
    ports:
      - "3000:3000"
    volumes:
      - $PWD/grafana:/var/lib/grafana
    networks:
      - dbnet
  jaeger:
    image: jaegertracing/all-in-one:1.23
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411

networks:
  dbnet:
